env:
  browser: true
  node: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - standard
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    - jsx: true
plugins:
  - '@typescript-eslint'
  - react
  - promise
  - import
  - unused-imports
rules:
  sort-imports: 0
  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  '@typescript-eslint/no-unused-vars': off
  unused-imports/no-unused-imports-ts: warn
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': off
  'react/prop-types': off
